---
- name: debian | Installing pre-requisite, git
  apt:
    name: ['git']
    state: present
  become: true

- name: install | Downloading Digital Rebar Source
  get_url:
    url: "{{ digital_rebar_source_dl }}"
    dest: "/tmp/{{ digital_rebar_package }}"
    checksum: "sha256:{{ digital_rebar_source_sha256 }}"

- name: install | Extracting Digital Rebar Source
  unarchive:
    src: "/tmp/{{ digital_rebar_package }}"
    dest: /tmp
    remote_src: true
  register: _digital_rebar_extracted
