---
- name: Installing source pre-requisite, go
  include_role:
    name: neutron37.ansible-golang

- include_tasks: debian_source.yml
  when: ansible_os_family == "Debian"



# - name: build | Build Digital Rebar Packages

# - name: install | Copying Digital Rebar Packages
#   copy:
#     src: "/tmp/bin/linux/amd64/{{ item }}"
#     dest: "{{ digital_rebar_install_dir }}/{{ item }}"
#     mode: "u=rwx,g=rx,o=rx"
#     remote_src: true
#   become: true
#   with_items:
#     - drpcli
#     - dr-provision
#     - incrementer
#   when: >
#         not _digital_rebar_install_check['stat']['exists'] and
#         _digital_rebar_extracted['changed']
#
# - name: install | Creating /var/lib/dr-provision
#   file:
#     path: /var/lib/dr-provision
#     state: directory
#   become: true
