---
- name: Installing source pre-requisite, go
  include_role:
    name: neutron37.ansible-golang

- name: debian | Installing pre-requisite, git
  apt:
    name: ['git']
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: install | Downloading Digital Rebar Source
  get_url:
    url: "{{ digital_rebar_source_dl }}"
    dest: "/tmp/{{ digital_rebar_package }}"
    checksum: "sha256:{{ digital_rebar_source_sha256 }}"

- name: install | Extracting Digital Rebar Source
  unarchive:
    src: "/tmp/{{ digital_rebar_package }}"
    dest: /tmp
    remote_src: true
  register: _digital_rebar_extracted

- name: "build | Build Digital Rebar Packages in {{ digital_rebar_source_dir }}/tools"
  command: "./build.sh 'arm:7:linux'"
  args:
    chdir: "{{ digital_rebar_source_dir }}/tools"
  environment:
    PATH: /usr/local/go/bin:/usr/bin:/sbin:/bin

# - name: install | Copying Digital Rebar Packages
#   copy:
#     src: "/tmp/bin/linux/amd64/{{ item }}"
#     dest: "{{ digital_rebar_install_dir }}/{{ item }}"
#     mode: "u=rwx,g=rx,o=rx"
#     remote_src: true
#   become: true
#   with_items:
#     - drpcli
#     - dr-provision
#     - incrementer
#   when: >
#         not _digital_rebar_install_check['stat']['exists'] and
#         _digital_rebar_extracted['changed']
#
# - name: install | Creating /var/lib/dr-provision
#   file:
#     path: /var/lib/dr-provision
#     state: directory
#   become: true
