---
# tasks file for ansible-digital-rebar-multiplatform
- name: main | Check if Digital Rebar is already installed
  stat:
    path: "{{ digital_rebar_binary }}"
  register: _digital_rebar_installed

- name: main | Install Digital Rebar if not yet installed.
  include_tasks: install.yml
  when: not _digital_rebar_installed['stat']['exists']
